version: '3'
services:
  # Define the Next.js application
  web:
    image: nextjs-app  # This is the image of your Next.js app
    build: .
    ports:
      - "3000:3000"  # Expose the Next.js app on port 3000
    volumes:
      - .:/app  # Mount the current directory for live code updates (optional)
      - /app/node_modules  # Exclude node_modules from being overwritten
    environment:
      DATABASE_URL: postgresql://postgres:password@db:5432/workmanager  # Connection string to PostgreSQL
      EMAIL_USER: workmanager.uni@gmail.com
      EMAIL_PASS: asja ychq uvmg vsdp
      NEXTAUTH_URL: http://localhost:3000
      NEXTAUTH_SECRET: wf0qPHVDOYuXOmZrb8TJj2mW7ff7N3YsNxNQrP2DZl44
      NEXTAUTH_SALT: 10
      GOTENBERG_URL: https://gotenberg.finnegan.dev
      TEMPLATES_GITHUB_REPO: https://github.com/Finnegan1/WorkManagerPDFTemplates.git
    depends_on:
      - db  # Ensure PostgreSQL service starts before the Next.js app
    command: npm run dev  # Start the app in development mode (change to `npm start` for production)

  # Define the PostgreSQL database
  db:
    image: postgres:15-alpine  # Use the official PostgreSQL image
    volumes:
      - postgres-data:/var/lib/postgresql/data  # Persist PostgreSQL data
    environment:
      POSTGRES_USER: postgres  # Set the default user
      POSTGRES_PASSWORD: password  # Set the default password
      POSTGRES_DB: workmanager  # Set the default database name

# Define volumes to persist database data
volumes:
  postgres-data:
